# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - readingtime

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore src/ReadingTime6.Web/ReadingTime6.Web.csproj

    - name: Build
      run: dotnet build src/ReadingTime6.sln --no-restore

    - name: Publish
      run: dotnet publish src/ReadingTime6.sln --configuration Release
      # run: dotnet publish src/ReadingTime6.Web/ReadingTime6.Web.csproj --configuration Release --no-build --output ./output
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
          name: .net-app
          path: /home/runner/work/ghas_hol/ghas_hol/src/bin/Release
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'preview'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F555B5C881714A0F97305C1AFEA795D0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D5D3DECF962A4FE096B4A27DB85EF391 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8183C33D348844C295F82CF72DB6F362 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'readingtime'
          slot-name: 'preview'
          package: .
          
