name: Deploy to Azure Preview Environment

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ReadingTime6.Web
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./output

    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'readingtime' # replace with your App Service name
        slot-name: 'preview' # replace with your Slot name
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1D77A2D5B0D24556B4A0B8D98C6B737D }}
        package: './output'
